sudo: required
language: node_js
services:
- docker
node_js:
- 8.0.0
env:
  matrix:
  - CXX=g++-4.8
  global:
  - DOCKER_IMAGE_NAME=kimwijk/silver-train
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: dnHamUfL2sI7bncZ1ed01TG1l7ZOIc6tZMrzt1mMWovwrVd2WHr+BuZm0PwLhNbAcrVR1HuUjp4koj6rGOilVaof6aZupGx/KgVK2pUd5rj8arBfkoCam9U8GfScxAZS8jc/T2sj8I7J/0N+msgRsLIh2QmiOEzs4b6cs8BzN4qGa4Tto5imGwuYVHfDj/4zfRUojecM65jZnElzoFUHeURulOy6yf37DdEVG5KZF/+xsvExMCGulqFppCgpKgsvUndw8vcE8uKMlowy+lFBx5UA3ASYY18Mvlas+PjFVs+3C41zmdJN89gr7LC9TVgGewI1Ky+7yqcCHLYu3nJBL49FWvS73f5Vdt5/sxecBfp80n1AAXf+3oQ/31ZQqJf6H0o9wlRyxEAkvn7Y081tXjIqfxFhkVwAiiaCK4M4y7dGVQeCorBTb7kATWeEd1Z9c75RrDvzNM2GjU3X9k4/OKaWvJl5/r+08WdtbkCTHXfO8pXUahaS/rfVp3I4AtDRJW4V0qOr30sEpkAdeQFMQlMANtq7sF6VTkAi0xAGQAKdjg5KG5N/L6y1AfoZIPDufAeKxyx5lUVcnYusC0rjQWuF9TqoJHI5oo4KoPetZsEgMwQdN2pekNVYWSojNnEiAWTk0aHCrNcg+uM70Sgu2JaLtehaSaiIBbGmMp1pypw=
  - secure: BUVBz9nqCJjot61K6mGWAvsxC1wFf+yFnPDkKIh+sYISkDZPx3U9tlpPPLSaUQY6JolQEsw2S/JR2cCE15zBwRUPa9yFNycN7Yf6KYDAdQDr7YyqgG2cMRTyXx7YKsz0KVAymcjIcyTGkV+qH18zsMdtxQPBi5ezrrTtodkXczTOJwVVgP/7VyjkYWd6edyALpKhvvLflnY+XVrZZ/N/QxfC3cz6pULcMc4c/D9xvTV1EsXAHq2Bh5XTA6xK9Aem91tCl2chaJANo9hYfUf+xhXD4Pcw4VCb4i7iW/I4i0oHqmJ1LGz5w0ZqM0KtDtywXQGddb+vQn+C2TafjwMc5RYSQwKdkbv/n73h/pBQNLpSwjcMKv3ufiG3f7RsYK2gt4IzTpWzwF0Zm0lpom2ivWmwrJrTE8byn0OQOKE2wOsA3DQSCLoStSEKjaH2WL7LBJXxpJNDXLFCGkOaQAYYW5QL9YHabeCIc9MYVCSPeFkKqBdV4oDfCXtkNf/EXj+t+YWVLCJVywssg87HICig9/7c7BesRSkA6tyeJUWl4tYXjZ19AAWv6JMuySsGKGLFXAffmUI+kG+Aiw77808T5Af1RPtBW+wXeLN3PUquXCjujae+/Jk1N1mYuSRVLNUYnxt1rQu5rFrJMjmHoVDKPQhddKJwKB0+GeyolxuIIXk=
  - secure: PpiToUt920yTzQBNZfJCsEZo2DJl4vNO1yJJ0NmOw8j0rc+oBAZGtugGzHSArv2b+YeemAy0dTQpbmlxL1gazV2UXGg49ngQV2BPBqSzZywlYfOrnS1k7VpevEuFMDyRlnp2igB4rlQw3iTU/NeDl55gtdgyzncUTIsFCmrmFs+5XkHgQGJFMofpY7afdjrOUaSMAjCLhq41VDdt3aCa/2RjuFSPHJQE1iKyJPmrcrVYNMvJorh2G83Zg3vNs1wAHbFXHPAj4q51qMUZONc0oraPl1it0fG87cs+wjExkPE0GVHjFvjhTpTQC30hrjDdbTqCzYiQW/GiJL78hyWC0oZ2PXnx4P9mEj29HCUwNKnJ7BSVTazTDR0rFjI/pzOh1hGL2TG/TA1fUVJonNAabCwxhAMCGcQzalMOrl8nHOEZjCNUCQztRHSZY/7znxhNZ4IH7theDbfblNT7kv3LtkYa8odCBzm18HYPZQB94xYtyWjixEfedkw3R8Z6/osWE2mcBd+6EpaVyfBm63fW35hqK6ZZ+PLaQ1FSid0yOUW/dCXDPl4Ihnh7RAxacCNusryvcie1qSiJzcjdcH28Fl7aesZjMMkDh8rFiwN4Co5DdWp2L82nnK+tgWxNEtTe8RbGti5lWC3sGSYKBkZzIil7xJbMPKGlEBZYN2U8WDs=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $DOCKER_IMAGE_NAME;
  fi
